dictionary:
  filename: assets/dictionaries/opencpop-strict.txt
  reserved_tokens: 3
rhythmizer:
  url: https://github.com/equal-singer/DiffSingerMiniEngine/releases/download/v0.0.1/rhythmizer.onnx
  filename: assets/rhythmizer/rhythmizer.onnx
acoustic:
  url: https://github.com/equal-singer/DiffSingerMiniEngine/releases/download/v0.0.1/acoustic.onnx
  filename: assets/acoustic/acoustic.onnx
  speedup: 10
vocoder:
  url: https://github.com/equal-singer/DiffSingerMiniEngine/releases/download/v0.0.1/vocoder.onnx
  filename: assets/vocoder/vocoder.onnx
  num_mel_bins: 128
  hop_size: 512
  sample_rate: 44100
  force_on_cpu: true
server:
  port: 9266
  cache_dir: cache/
  max_threads: 1
providers:
  - name: CUDAExecutionProvider
    options:
      device_id: 0
      cudnn_conv_algo_search: DEFAULT
    attributes:
      cuda_path: path/to/your/cuda/dlls
      cudnn_path: path/to/your/cudnn/dlls
  - name: DmlExecutionProvider
    options:
      device_id: 0
  - name: CPUExecutionProvider
    options: {}
